# Generated by Django 3.0.8 on 2020-07-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('real_name', models.CharField(max_length=64)),
                ('tz', models.CharField(max_length=64)),
            ],
        ),
    ]
