# Generated by Django 3.0.8 on 2020-07-08 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_activityperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityperiod',
            name='activity_periods',
            field=models.ForeignKey(default='DEFAULT VALUE', on_delete=django.db.models.deletion.CASCADE, to='myapp.User'),
        ),
    ]
