# Generated by Django 3.0.8 on 2020-07-08 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_activityperiod_activity_periods'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityperiod',
            old_name='activity_periods',
            new_name='user',
        ),
    ]
